name: Upload Artifacts

on:
  push:
    branches: [ master ]
    paths:
      - 'src/main/**'
      - 'pom.xml'
      - '.github/workflows/artifacts.yml'

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build Artifacts
        run: mvn clean package --batch-mode
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: target/*.jar